name: Check Quarkus release & ingest

on:
  schedule:
    - cron: "0 22 * * *"  # 09:00 AEDT (UTC+11)
    - cron: "0 23 * * *"  # 09:00 AEST (UTC+10)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: quarkus-ingestion
  cancel-in-progress: false

jobs:
  check-and-run:
    runs-on: ubuntu-latest
    env:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      # Let GitHub API calls reuse the same PAT if needed:
      GITHUB_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Gate to 09:00 Australia/Melbourne
        id: gate
        run: |
          HOUR="$(TZ=Australia/Melbourne date +%H)"
          echo "Local Melbourne hour: $HOUR"
          if [ "$HOUR" = "09" ]; then
            echo "run=yes" >> "$GITHUB_OUTPUT"
          else
            echo "run=no" >> "$GITHUB_OUTPUT"
            echo "Not 09:00 in Melbourne; exiting."
          fi

      - name: Run check-and-run.sh
        if: steps.gate.outputs.run == 'yes'
        shell: bash
        run: |
          set -euxo pipefail
          ./scripts/check-and-run.sh
